<?php
get_template_part('/inc/functions/clear');
get_template_part('/inc/functions/add-js');
get_template_part('/inc/functions/add-styles');
get_template_part('/inc/functions/replaces-query-version');
get_template_part('/inc/functions/add-menu');
get_template_part('/inc/functions/add-html5');
get_template_part('/inc/functions/add-favicon');
get_template_part('/inc/actions/index');
?>